### ISSUE TITLE
Execute Apex Error

### ISSUE THREAD

**Issue by GusjkoA** [joeferraro/MavensMate-Desktop#105]
While trying to execute apex anonymously inside the MavensMate App an error is generated:
Error: Could not create Trace Flags: LogType is required.: LogType

![image](https://cloud.githubusercontent.com/assets/1788693/10826220/8fdb0b8c-7e60-11e5-9cbe-7932fa055510.png)

**Comment by brosiusad** [comment]
I am getting this exact same error 

MM-app v0.0.10
MM-ST v7
OSX 10.10.5

**Comment by idanblich** [comment]
++
MM-app v0.0.10
MM-ST v7 b1
OSX 10.11

**Comment by ralphcallaway** [comment]
see https://github.com/joeferraro/MavensMate-app/issues/66 and https://github.com/joeferraro/MavensMate/issues/602 for details on this and workarounds until a patch goes live
