### ISSUE TITLE
MM is trying to save to wrong tab/filename.

### ISSUE THREAD

**Issue by deckblad** [joeferraro/MavensMate-Desktop#106]
Sometimes when I have multiple tabs open in Sublime. And, I hit CTRL+SHIFT+S to compile the current tab, it'll instead try to push that tab's contents to a different metadata object open in another background tab. If I close the mistaken background tab and try again, MM may try to save to yet another background tab's object.

It seems this might only be when there's tabs open to the right of the current foreground tab. I'm not certain.

Compile on save is off.

**Comment by amorek** [comment]
https://github.com/joeferraro/MavensMate-app/issues/88

Ctrl+SHIFT+S Saves all open tabs now. And yes, I also experienced metadata of one object pushed to other object.
