### ISSUE TITLE
Request: better "members" control in package.xml

### ISSUE THREAD

**Issue by ScriptMonkey00** [joeferraro/MavensMate-Desktop#108]
Just wondering if there's a feature/option that will suppress the use of "*" as a members reference when all are selected in the edit package options.

In a multi-developer environment using multiple orgs and sharing with git, it's much more functional to explicitly itemize the classes/objects/pages/etc by name, but when all are checked it just uses *.  This means the workaround is to manually type all the file names, or add a meaningless one and just unselect it.

I wonder if there is, or could be, an option to never use * when MavensMate builds the pacakge.xml file.

Thanks so much.

**Comment by GusjkoA** [comment]
That would be very helpful
