### ISSUE TITLE
Invalid Password when using MM-App

### ISSUE THREAD

**Issue by alex-martin-xactium** [joeferraro/MavensMate-Desktop#111]
If for what ever reason, my org details are incorrect (wrong sec token, invalid password, expired password),  the MavensMate-App won't let me change the details. Just keeps displaying the error. 
<img width="1001" alt="screenshot 2015-11-30 16 12 32" src="https://cloud.githubusercontent.com/assets/9659346/11476946/523be93c-977d-11e5-963c-bc766333d585.png">

Any work arounds for this?

**Comment by zjeh** [comment]
See my comment at https://github.com/joeferraro/MavensMate/issues/595#issuecomment-161041499
