### ISSUE TITLE
Project doesn't reside in mm_workspace

### ISSUE THREAD

**Issue by alex-martin-xactium** [joeferraro/MavensMate-Desktop#112]
![screenshot 2015-12-03 11 05 52](https://cloud.githubusercontent.com/assets/9659346/11559008/d4d6257e-99ad-11e5-80ba-6649faa274ba.png)

getting the above error after trying to update the subscription in MM-App. Using the latest atom editor, but the folder most certainly exists in the workspace, as it worked fine before.

**Comment by viraj89** [comment]
Did you cross checked the workspace and it's syntax intact? 
Request to paste it below and/or refer this - 
https://github.com/joeferraro/MavensMate-SublimeText#important-settings

**Comment by alex-martin-xactium** [comment]
<img width="643" alt="screenshot 2015-12-22 10 18 00" src="https://cloud.githubusercontent.com/assets/9659346/11953077/4d98e5e6-a895-11e5-8a8f-28c9b20309e2.png">

When I come across this error, I end up having to delete the whole project and recreating it. Not much of an issue, as all the code is on git anyway. Not had it happen in a few weeks now, so very intermittent. 

Sorry for late reply.
