### ISSUE TITLE
Has Development Stopped?

### ISSUE THREAD

**Issue by banderson5144** [joeferraro/MavensMate-Desktop#116]
Just want to make sure in case I should switch back to a stable in development project

**Comment by Galiaf47** [comment]
The same question.
Don't see any updates for a long time.

**Comment by mikepaisner** [comment]
I am using V6 of MavensMate within Sublime Text 3.  I recently started getting prompted to update to a new version upon login.

Is this update a new version on the V6 branch or will this push me to V7?

V6 is working well for me and I'd rather not go to V7 unless it is really ready.

Mike

**Comment by nbdesai** [comment]
sad :(

**Comment by banderson5144** [comment]
Just saw a commit to this repo yesterday. @joeferraro are there updates being worked on?

**Comment by kylethornton** [comment]
Updates are being made. @joeferraro had some time off for family.
