### ISSUE TITLE
Allow developer to control package.xml outside of MM

### ISSUE THREAD

**Issue by ckoppelman** [joeferraro/MavensMate-Desktop#132]
As a developer, I should be the final authority on what `package.xml` looks like.  Currently, when I run "Clean Project", package.xml resets to whatever MM calculates it should be.  This means that on my computer, it will look different than on my colleague's computer because we may have configured MM-app differently.

This is particularly annoying in conjunction with not being able to set a metadata api version on a project level.  `package.xml` is the traditional way to establish this, but MM-app does not seem to respect that. (#133)

**Comment by djorgji** [comment]
We version control the package.xml, so we keep having to reset it in git before doing commits etc, the package.xml should be readonly.
