### ISSUE TITLE
The application "MavensMate.app" can't be opened on Mac, can only open from disk image "MavensMate.dmg"

### ISSUE THREAD

**Issue by TigMH** [joeferraro/MavensMate-Desktop#137]
When I try to open MavensMate from the applications folder, I get the following error: The application "MavensMate.app" can't be opened. 

I was finally able to open the app from the disk image "MavensMate.dmg".  This is counter-intuitive, and I usually eject the disk image and delete the dmg.  I don't like a cluttered desktop.

I tried dragging the MavensMate.app from the disk image to the Applications folder.  It replaces the existing application, but I still can't open it from here.

How do I correct this issue?

**Comment by srosen** [comment]
I am having the same issue as well.

**Comment by nickforce** [comment]
I am facing this issue as well.

**Comment by DallasDeuce** [comment]
Same issue

**Comment by donmac23** [comment]
Same. Dang. I can also run directly from disk image but still have a problem in getting the sublime plugin to upgrade to v7 (and yes, I have added entry under install_prereleases for Mavensmate, as per [these instructions](https://github.com/joeferraro/MavensMate-SublimeText#version-7-betas) )

**Comment by yippie** [comment]
I had this issue as well.  I fixed it by doing the following (note, I used a shotgun approach so it is possible not all of these are required):

1) Download Onyx Mac OS utility from http://www.titanium.free.fr/
2) Onyx -> Maintenance -> Permissions
3) Onyx -> Maintenance -> Rebuilding
  - LaunchServices
  - dyld's shared cache
  - XPC cache
  - CoreDuet Database
4) Reboot

Of the above, the only one I know is required is the reboot as I tried to open it after step 3 and it still didn't open.
