### ISSUE TITLE
Error initializing project: Could not start system streaming listener: Cannot read property 'NodeHttp' of undefined.

### ISSUE THREAD

**Issue by chechtic** [joeferraro/MavensMate-Desktop#141]
after update with newest release for mac

**Comment by joeferraro** [comment]
Are you behind a proxy?

**Comment by chechtic** [comment]
No I m not behind a proxy

**Comment by sevem** [comment]
Same problem and also not behind a proxy. Problem exists not only while initializing the project. Same problem e.g. on indexing or metadata

**Comment by fusion27** [comment]
### I'm seeing the same thing

* Stacks of thanks for all of your hard work, Joe 👍 
* I'm also not behind a proxy
* Screenshot:
![mavensmateinitialize-01](https://cloud.githubusercontent.com/assets/608738/17587980/c09a67de-5f99-11e6-89ff-bd58acbe708e.jpg)

**Comment by chechtic** [comment]
Yes of course, it's good job Joe 👍  thank you
