### ISSUE TITLE
v0.0.11-beta.1 Can't scroll-x on test results

### ISSUE THREAD

**Issue by kylethornton** [joeferraro/MavensMate-Desktop#143]
Run unit tests that fail. if the window isn't wide enough you can't see results without making window wider. Should be able to scroll the test results horizontally.

**Comment by joeferraro** [comment]
Screenshot plz :)

**Comment by joeferraro** [comment]
@kylethornton can you post all issues to https://github.com/joeferraro/MavensMate? We'll be closing issues here soon

**Comment by kylethornton** [comment]
sure thing.
