### ISSUE TITLE
[ERROR]: ENOENT when refreshing Apex Class

### ISSUE THREAD

**Issue by devinboots** [joeferraro/MavensMate-Desktop#145]
Can't communicate with server due to this error:

[ERROR]: ENOENT: no such file or directory, lstat 'C:\Users\J~1.SMI\AppData\Local\Temp\mm_116812-5396-1k5h0g5\unpackaged'

Occurs on refresh and save

**Comment by joeferraro** [comment]
Sounds like an antivirus/permissions issue. Do you experience this issue if you run Desktop as an admin?

**Comment by devinboots** [comment]
Yes.  Still happens with both MM app and Sublime running as admin

**Comment by kidtsunami** [comment]
@joeferraro could this be related to the username having a ~ (tilde) in it? I know that should be interpreted literally, but wondering if some path library somewhere down the line is trying to interpret it as a relative path?

**Comment by devinboots** [comment]
The username is from the error, but my username is in the form "first.last" with no "~".  The path is correct until "\unpackaged" as the "mm_116812-5396-1k5h0g5" folder exists but is empty.

**Comment by joeferraro** [comment]
1. What version of Windows are you using? And are you 32 or 64 bit?
2. Are you using antivirus? If so, which?
3. Can you produce a log and attach it to this issue?

**Comment by devinboots** [comment]
Windows 7 Enterprise 64 bit
McAfee
I've set a folder for the mmst.log to be created in the plugin settings and the same folder in MM app settings.  However, no .log file is created before the error is thrown.  Is there another setting I missed?

**Comment by joeferraro** [comment]
@devinboots if you temporarily disable McAfee, does your operation complete successfully?

**Comment by devinboots** [comment]
I was able to get a log file...generated due to a different error when refreshing Custom Metadata, but added the ENOENT error when trying to refresh classes.
[mmst.txt](https://github.com/joeferraro/MavensMate-Desktop/files/470452/mmst.txt)

**Comment by joeferraro** [comment]
> @devinboots if you temporarily disable McAfee, does your operation complete successfully?

**Comment by devinboots** [comment]
The ENOENT error was from refreshing classes.  Got a Result: [ERROR]: Cannot read property 'inFolder' of undefined when refreshing CMT.

Working with IT on access to McAfee

**Comment by devinboots** [comment]
Getting a couple new errors as well now:
Project 1: On classes refresh -> [OPERATION FAILED]: No response from mavensmate executable.
Project 2: On classes refresh -> [ERROR]: Request to the local MavensMate server failed. Error initializing project: Unexpected string

**Comment by joeferraro** [comment]
@devinboots given you are experiencing issues, you may want to try https://github.com/joeferraro/MavensMate-Desktop/releases/tag/v0.0.11-beta.2

**Comment by devinboots** [comment]
Installed the beta version....
Getting both errors listed above and here a second time:
Project 1: On classes refresh -> [OPERATION FAILED]: No response from mavensmate executable.
Project 2: On classes refresh -> [ERROR]: Request to the local MavensMate server failed. Error initializing project: Unexpected string in JSON at position 587

**Comment by joeferraro** [comment]
1. What version of the Sublime Text plugin are you running?
2. Is this a brand new project or an existing project you created before you updated?
3. If it's an existing project, do you have this issue if you create a new project?
4. Can you please generate a log and paste it to this issue? To generate logs, configure them via MavensMate Desktop Settings > log level, MavensMate Desktop Settings > log location

**Comment by joeferraro** [comment]
Moving to this thread: https://github.com/joeferraro/MavensMate/issues/720

**Comment by devinboots** [comment]
1. v7.0.0
2. Existing
3. After creating a new project with the newest beta version of the MM app, I attempted to refresh a class and received the original error from this thread:
Result: [ERROR]: ENOENT: no such file or directory, lstat 'C:\Users\FIRST~1.LAS\AppData\Local\Temp\mm_116814-14292-80mxz9.zb7aybke29\unpackaged'
4. log is attached
[mavensmatelog.txt](https://github.com/joeferraro/MavensMate-Desktop/files/472883/mavensmatelog.txt)
