### ISSUE TITLE
oAuth Doesn't seem to work for sandboxes

### ISSUE THREAD

**Issue by jimrae** [joeferraro/MavensMate-Desktop#147]
Have the Beta (0.11 beta 2) installed. When I open a project, I get the "reauthentication required" message, and when I try to re-authenticate, with un and pw, and select "Sandbox" for the "Salesforce Environment Type" my username and password are not accepted.  If I use "Custom Domain" and put in "https://test.salesforce.com" it works correctly.

Appears that selecting the different environment types from the drop down does not work correctly. Also, if I connect to a project that is linked to Production, and select the "Production" option, it does work correctly.

**Comment by joeferraro** [comment]
resolved in 0.0.11-beta.3
