### ISSUE TITLE
Error when saving -  [ERROR]: result.resolve is not a function

### ISSUE THREAD

**Issue by akershteyn** [joeferraro/MavensMate-Desktop#148]
Installed new MavensMate app v0.0.11-beta.3 on Windows 7
Connected to the project from MM app. 
Opened project in sublime-text editor. 
Tried to modify something save the changes
Getting following error:  
Timestamp: Thu, 15 Sep 2016 11:24:08
   Result: [ERROR]: result.resolve is not a function. 
I am getting this error regardless what i try to change/save

**Comment by akershteyn** [comment]
the same message when trying refresh from server

**Comment by akershteyn** [comment]
Seems like the issue resolved by updating MM app setting:  

## The full path of your Sublime Text executable (Sublime Text users only). 

Mine was  "windows": "C:\\Program Files\\Sublime\\sublime_text.exe",    
vs  
default value ... \\Sublime text 3\\sublime_text.exe",    

working now.

**Comment by joeferraro** [comment]
@akershteyn oh wow, thanks for uncovering this. Re-opening as a bug

**Comment by joeferraro** [comment]
This issue was moved to joeferraro/MavensMate#729

**Comment by LucasDuque** [comment]
Thanks for this, very useful for me, who was with same problem
