### ISSUE TITLE
Mavensmate javascript error.

### ISSUE THREAD

**Issue by yogeshdhaneshwar** [joeferraro/MavensMate-Desktop#150]
Platform : Windows 10.

when opens MavensMate it is giving javascript error.

**Comment by yogeshdhaneshwar** [comment]
![mavesmate_error1](https://cloud.githubusercontent.com/assets/17423953/19330389/06ea216e-9093-11e6-819e-3cc34d3f0abc.JPG)

**Comment by jimrae** [comment]
This isn't a Javascript error. If you look at the error, the EADDRINUSE message indicates that the port is in use.  Either, you have 2 applications using the same port, or, you are trying to launch 2 copies of Mavensmate.

**Comment by joeferraro** [comment]
Also, please do not create issues in this repository, as the message indicates when you try to create an issue.
