### ISSUE TITLE
Slow performance using lightning on Mac

### ISSUE THREAD

**Issue by jesusCanteroMakepositive** [joeferraro/MavensMate-Desktop#152]
When I work with Mavens Mate with Ligthning components after a couple of save or refresh actions my computer become so slow. I've take a look in the Activity Monitor and they are running a few force processes that are using a huge percentage of my CPU at between 80 to 99. I need to quit those processes and my computer come back to normal performance until I save or refresh a couple of time.

I'm working with
Sublime Text 3 build 3126
Mavens Mate v.0.0.11-beta 6 (I've update from v.0.0.10 because I've the same issue)
MacosX El Capitan v10.11.6

Thanks in advanc

**Comment by joeferraro** [comment]
All issues are now handled in the central MavensMate repository, as noted by the [README](https://github.com/joeferraro/MavensMate-Desktop#issues) and in [the note you are presented](https://github.com/joeferraro/MavensMate-Desktop/issues/new) when you attempt to create a new issue on this repository. Please help us out by not creating new issues in this repository. Thanks.
