### ISSUE TITLE
Unable to create New Project in Mavensmate desktop application in app-0.0.11-beta7 version

### ISSUE THREAD

**Issue by saranya-gotrala** [joeferraro/MavensMate-Desktop#153]
After providing credentials it will display as follow
![mavensmate intialize](https://cloud.githubusercontent.com/assets/23525621/20392294/2b875e02-acfd-11e6-8d06-7654740ceb5f.PNG)

after that it will redirect to blank screen. So can anyone please help on these issue
![later](https://cloud.githubusercontent.com/assets/23525621/20392371/91a8d09e-acfd-11e6-8b5b-97226715e7b0.PNG)

*****

Please do not create a new issue in this repository, we've left issues open on this project for SEO/historical purposes *only*. If you need to create an issue, please do so at the central MavensMate issues repository: https://github.com/joeferraro/MavensMate/issues

Thank you!

*****
*****

**Comment by joeferraro** [comment]
All issues are now handled in the central MavensMate repository, as noted by the [README](https://github.com/joeferraro/MavensMate-Desktop#issues) and in [the note you are presented](https://github.com/joeferraro/MavensMate-Desktop/issues/new) when you attempt to create a new issue on this repository. Please help us out by not creating new issues in this repository. Thanks.

**Comment by proprateek** [comment]
I am getting the same problem. Can anyone please help me out for this.

**Comment by kidtsunami** [comment]
@proprateek please submit an issue to the main MavensMate repository here https://github.com/joeferraro/MavensMate/issues
