### ISSUE TITLE
Missing ApexClass

### ISSUE THREAD

**Issue by buggyb12** [joeferraro/MavensMate-Desktop#158]
I have switched to API v40.0 suddenly ApexClass type of metadata disappeared. I am using version 0.0.11 on windows 8.

**Comment by buggyb12** [comment]
This looks like it is only one off happens for only one of the projects after i switched to v40.0 api. Will investigate to get more details.

**Comment by pbattisson** [comment]
As per the update on the central repository (https://github.com/joeferraro/MavensMate) MavensMate is no longer being actively developed or supported. We recommend using Salesforce's official Visual Studio Code plugin for building Salesforce applications.
