### ISSUE TITLE
Unable to find deploy to server option after validate Deployment

### ISSUE THREAD

**Issue by soruebo** [joeferraro/MavensMate-Desktop#159]
Unable to find deploy to server button in mavens mate.. I don't know weather it is issue or need to set path

**Comment by pbattisson** [comment]
As per the update on the central repository (https://github.com/joeferraro/MavensMate) MavensMate is no longer being actively developed or supported. We recommend using Salesforce's official Visual Studio Code plugin for building Salesforce applications.
