### ISSUE TITLE
Mavensmate desktop app not able to create a project

### ISSUE THREAD

**Issue by praveenmakam2012** [joeferraro/MavensMate-Desktop#160]
*****
I installed the latest version of mavensmate desktop app and tried creating a new project. It takes OAuth 2.0 flow route, asks for username and password, asks for access to mavensmate, successfully logs on and screen turns white. Nothing loads after that.

I tried installing and doing the same on my other laptop. But still the same, nothing shows up. I see it happening since very recently. Could you please check why?

*****

Please do not create a new issue in this repository, we've left issues open on this project for SEO/historical purposes *only*. If you need to create an issue, please do so at the central MavensMate issues repository: https://github.com/joeferraro/MavensMate/issues

Thank you!

*****
*****

**Comment by dapulache** [comment]
Have you found a workaround for this? I am experiencing the same thing.

**Comment by praveenmakam2012** [comment]
No. I installed previous version of mavensmate desktop app and started using it. Earlier version doesnt use OAuth, its manual.

**Comment by vram1980** [comment]
@dapulache I had this similar issue running the mac version of the app. Like @praveenmakam2012 mentioned I was able to connect using the .10 build. Hope this helps.

**Comment by pbattisson** [comment]
As per the update on the central repository (https://github.com/joeferraro/MavensMate) MavensMate is no longer being actively developed or supported. We recommend using Salesforce's official Visual Studio Code plugin for building Salesforce applications.
