### ISSUE TITLE
1800 : There was a problem in setting up your remote access

### ISSUE THREAD

**Issue by KushalB** [joeferraro/MavensMate-Desktop#161]
Hi,
 I am using the MavensMate v0.0.11-beta.7 and I am stuck with a specific issue for couple of days and I need help to resolve this.

Steps that I took - 

- New Project, choosing Sandbox
- Salesforce login page comes up. Username & password are being provided. 
- After the processing animation a static error page comes up saying 

> We can't authorize you because of an OAuth error. For more information, contact your Salesforce ad
ministrator. 1800 : There was a problem in setting up your remote access. 

![screen shot 2018-12-24 at 1 22 25 pm](https://user-images.githubusercontent.com/11231174/50393843-03f2de00-077f-11e9-91e1-001d4f73cfd0.png)

*****
*****

Please do not create a new issue in this repository, we've left issues open on this project for SEO/historical purposes *only*. If you need to create an issue, please do so at the central MavensMate issues repository: https://github.com/joeferraro/MavensMate/issues

Thank you!

*****
*****

**Comment by pbattisson** [comment]
As per the update on the central repository (https://github.com/joeferraro/MavensMate) MavensMate is no longer being actively developed or supported. We recommend using Salesforce's official Visual Studio Code plugin for building Salesforce applications.
