### ISSUE TITLE
Deploying from Sublime to Salesforce

### ISSUE THREAD

**Issue by SteveFouracre** [joeferraro/MavensMate-Desktop#162]
I cant deploy anything to Salesforce from Sublime. I installed th portable version for windows at https://www.sublimetext.com/3

And this version of mavensmate MavensMate-Desktop-Setup-0.0.11-beta.7-ia32.exe
 at https://github.com/joeferraro/MavensMate-Desktop/releases

Metadata is retrieved no problem but I cant deploy.
I dont need to set a security token because Ive opened my IP address.

If I make a change like add a comment to a class, save, then go to Maven to deploy that class nothing changes in Salesforce. 

Steve

**Comment by pbattisson** [comment]
As per the update on the central repository (https://github.com/joeferraro/MavensMate) MavensMate is no longer being actively developed or supported. We recommend using Salesforce's official Visual Studio Code plugin for building Salesforce applications.
