### ISSUE TITLE
Cannot retrieve Custom Objects when Salesforce has a namespace

### ISSUE THREAD

**Issue by SteveFouracre** [joeferraro/MavensMate-Desktop#163]
I cant retrieve Custom Objects from Salesforce using Maven when the Custom Objects are added to a package I am building in Salesforce. 
Maven retrieves all standard objects and other Custom Objects not added to my package, it even retrieves all classes, pages etc that are added to my package which is strange. 

I installed the portable version for windows at https://www.sublimetext.com/3

And this version of mavensmate MavensMate-Desktop-Setup-0.0.11-beta.7-ia32.exe
at https://github.com/joeferraro/MavensMate-Desktop/releases

I set mm_ignore_managed_metadata to false in the package settings in Sublime and that fixed retrieving classes and pages etc but not Custom Objects 

Steve

**Comment by pbattisson** [comment]
As per the update on the central repository (https://github.com/joeferraro/MavensMate) MavensMate is no longer being actively developed or supported. We recommend using Salesforce's official Visual Studio Code plugin for building Salesforce applications.
