### ISSUE TITLE
Minimum window height exceeds laptop retina resolutions

### ISSUE THREAD

**Issue by nwoolls** [joeferraro/MavensMate-Desktop#17]
It seems impossible to resize the main window any smaller than a height that exceeds the resolution on my fairly recent laptop.

**Comment by joeferraro** [comment]
@nwoolls what resolution is that?

**Comment by nwoolls** [comment]
@joeferraro Sorry for the omission, it's 2560 x 1600 (MacBook Pro Retina, 13-inch, Late 2013).

**Comment by pfeilbr** [comment]
@nwoolls @joeferraro looks like it's related to [electron issue 2714](https://github.com/atom/electron/issues/2714) dealing with min-width and max-width

**Comment by nwoolls** [comment]
It may be but I am not running Windows on the MacBook in question.
