### ISSUE TITLE
Proxy settings causing connectivity issue on Windows 7

### ISSUE THREAD

**Issue by BUONJG** [joeferraro/MavensMate-Desktop#24]
Hello,

Since yesterday Sublime package update, I can't use MavensMate.

I got the auto install of the package in Sublime suddently nothing was working.

I read the release note:
- I installed MavensMate-app
- I start the app
- I change the settings (proxy settings included)

I can see the Salesforce projects I have but when I try to open it I have the error below: 
![image](https://cloud.githubusercontent.com/assets/898114/10185698/2bbe009a-674b-11e5-815f-140b02f2f415.png)

Also when I try to create a new project I have the same error message:
**tunneling socket could not be established, cause=getaddrinfo ENOTFOUND armony armony:80**

My station is running on Windows 7.
I'm trying the app behind my company proxy server.

Also, sublime text do not recognize the MavensMate-app:

I still have the error message below:

MavensMate for Sublime Text v5.0.0
[ERROR]: Could not contact local MavensMate server, please ensure MavensMate-app is installed and running (https://github.com/joeferraro/mavensmate-app/releases). MavensMate will not run properly until resolved. For more information, please visit https://github.com/joeferraro/MavensMate-app#mavensmate-app

And I confirm mavensmate-app is installed and running fine.

This plugin is my favorite tool to work with salesforce, I would like to use it again as soon as possible.

Is there a way to come back to the previous version?

Regards,

**Comment by joeferraro** [comment]
We're looking into this. To roll back temporarily:

```
cd /sublime/text/packages/path
git clone https://github.com/joeferraro/MavensMate-SublimeText "MavensMate"
git checkout tags/v4.0.5
```

**Comment by rrcook** [comment]
I'm also having the issue about not contacting the MM server. I do not have any proxies to worry about.
Windows 7 Enterprise 64 bit. I tried both MavensMate 0.0.6 and the 0.0.5 mentioned in issue #22

**Comment by joeferraro** [comment]
@BUONJG would you mind trying this prerelease to see whether your proxy settings work? https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.7-beta1

**Comment by BUONJG** [comment]
Hello,

I succeed to roll back to package 4.0.5. Thank you.

I will try your new version tonight, I need to finalize some Salesforce dev right now...

I keep you informed.

Thank you very much for your support.

**Comment by joeferraro** [comment]
no worries, thanks!

**Comment by AkramGargouri** [comment]
@joeferraro : I installed v0.0.7-beta1 and I still facing the issue

**Comment by KoenVM** [comment]
Also having the same issue. Was trying the whole day to get it working again... I had issues because of the proxy before and then, using fiddler as an in-between proxy with the "Always Authenticate" option did the trick but here, it's not working.
With the old version, there were particular issues because only basic proxy authentication was possible. Not sure though if the new version better copes with proxies?
Really hope this can be fixed as also for me, it's my favorite IDE for Salesforce and wouldn't want to let it go.

**Comment by joeferraro** [comment]
@KoenVM have you tried configuring your proxy in 0.0.7-beta1?

**Comment by KoenVM** [comment]
Hey, not yet, I'll try that tomorrow.

**Comment by BUONJG** [comment]
Hello,

I tried the new version v0.0.7 but I still have the same error:
tunneling socket could not be established, cause=getaddrinfo ENOTFOUND armony armony:80

For your information, I'm using also a Windows 7 64bit laptop behind proxy and probably firewal (company computer)

Do you need a log file to follow your investigations?

Meanwhile I continue using the Sublime Package v4.

Thank you,

**Comment by joeferraro** [comment]
@BUONJG and you had your proxy configured in mm-app?

**Comment by BUONJG** [comment]
Yes, of course.

I just have a doubt concerning the special char escapes.

I tried with:
http://domain\user:password@proxy.server.net:8080
http://domain\\user:password@proxy.server.net:8080
http:\/\/domain\\user:password@proxy.server.net:8080

What is the proper way to set the proxy?

None of these worked.

Also, for directory setting (log, workspaces, ...) I put path as:
C:\\dir\\sub-dir

Is that ok?

When I start the app, I have the error below:
![image](https://cloud.githubusercontent.com/assets/898114/10206446/34099c42-67c7-11e5-86eb-f4b38923e111.png)

Regards

**Comment by KoenVM** [comment]
@joeferraro couldn't install the new version yet cause of no admin rights (*sigh* - I know...) . But had a look at the change you did for it, noticed you set the env variables which was something I also already tried by launching MM app through a .bat and before launching setting the HTTP_PROXY and HTTPS_PROXY too. No luck though.

**Comment by KoenVM** [comment]
@joeferraro I now installed your latest release (v0.0.7-beta4) and now it's working. I still get the following error though on start-up. But apart from that error, things seem to be working.
![image](https://cloud.githubusercontent.com/assets/2277975/10215627/981ca2d6-6823-11e5-85eb-4a5edac16262.png)

**Comment by KoenVM** [comment]
@joeferraro sorry for kinda spamming but got another small update... It worked FOR A WHILE :)... And then it stopped working. I was already thinking before that it's the proxy not getting the proper authentication or something and then it stops me after a few not-properly-authenticated requests. 
What I now did is installed and configured CNTLM and it works again. CNTLM is some sort of in-between proxy that will handle the NTLM type of proxy authentications which are often not supported by applications.

**Comment by AkramGargouri** [comment]
@joeferraro @KoenVM I installed the beta-4 also and it seem working behind a proxy #itsBeenALongDayWithoutYouMavensMate

**Comment by amitgithubuser** [comment]
i get below error when updating metadata in the project.
also after automatic update, i added my workspace path in the mavensmate app, then i click "Update Project" in my sublime text, it opens the screen in the app. And this screen doesn't show correct metadata components. when i try to update components , i get attached error

i am on windows 7 64 bit.

![mavensmate-error](https://cloud.githubusercontent.com/assets/5687840/10228768/2e90f828-683a-11e5-8957-995a97564cb3.PNG)

**Comment by zjeh** [comment]
I was also having the JavaScript errors at startup and timeout errors with projects, when behind a proxy.

Just installed v0.0.7 64bit and confirming both errors are resolved for me so far.

**Comment by BUONJG** [comment]
Hello,

I installed release v0.0.9-beta2 and I still have the same issue:
tunneling socket could not be established, cause=getaddrinfo ENOTFOUND armony armony:80

Do you have any idea how to solve the issue?

Do you need more information?

regards,

**Comment by KoenVM** [comment]
hey @BUONJG , could you try if installing CNTLM helps? It did for me. Here's a tutorial on how to set it up: http://stormpoopersmith.com/2012/03/20/using-applications-behind-a-corporate-proxy/ . After setting it up, don't forget to point to the proxy you will then have running on localhost.
