### ISSUE TITLE
MavensMate for Sublime Text v5.0.0 Stratup error

### ISSUE THREAD

**Issue by Gajendrasinh** [joeferraro/MavensMate-Desktop#29]
When i am create new project then getting error

MavensMate for Sublime Text v5.0.0

[ERROR]: Could not contact local MavensMate server, please ensure MavensMate-app is installed and running (https://github.com/joeferraro/mavensmate-app/releases). MavensMate will not run properly until resolved. For more information, please visit https://github.com/joeferraro/MavensMate-app#mavensmate-app

**Comment by joeferraro** [comment]
Platform? Do you have mavensmate-app installed and running?

**Comment by emiliocampa-hoyos** [comment]
Getting the same error here, I succesfully installed Mavensmate (It installed itself in Program Files (x86)) and got it to run. Once I click on "Open in Sublime" button, Sublime would throw that same error you are getting. Is there any way we could roll back to the version we had before?

**Comment by joeferraro** [comment]
@emiliocampa-hoyos https://github.com/joeferraro/MavensMate-app/issues/24#issuecomment-144397185

**Comment by Gajendrasinh** [comment]
Platform? Do you have mavensmate-app installed and running?

Platform : window 8 64bit

mavensmate-app installed  : No

can you give me link download


-
Best Regards,
Gajendrasinh Zala
