### ISSUE TITLE
Request to the local MavensMate server failed. No JSON object could be decoded

### ISSUE THREAD

**Issue by enriquegq** [joeferraro/MavensMate-Desktop#42]
- MavensMate-app up and running. I was able to retrieve a project without any problem.
- Opening the project in Sublime (no problem either)
- Trying to "refresh from server" a class and got the error:
"Request to the local MavensMate server failed. No JSON object could be decoded"

**Comment by joeferraro** [comment]
Can you please set up logging in mavensmate-app settings and paste any relevant logs? what platform are you on?

**Comment by enriquegq** [comment]
Windows 7 - behind proxy (but set in settings)

I get now this error from sublime console:
"Request to the local MavensMate server failed. <html><head><title>504 Gateway Timeout</title></head>
<body><h1>Gateway Timeout</h1>
<p>Server error - server 127.0.0.1 is unreachable at this moment.<br><br>Please retry the request or contact your adminstrator.<br></p>
</body></html>"

**Comment by enriquegq** [comment]
@joeferraro Here it is the log after running the refresh command:

Calling mavensmate adapter
OPERATION: refresh-metadata
{'body': {'paths': ['*C:\\..\\..\\className.cls*']}, 'context': <MavensMate.mavensmate.RefreshActiveFileCommand object at 0x0000000005618B38>}
http://localhost:56248/execute?command=refresh-metadata&async=1&pid=*ID*
posting to MavensMate:
b'{"paths": ["*C:\\\\...\\\\....\\\\className.cls*"]}'
response from MavensMate
<http.client.HTTPResponse object at 0x0000000005294400>
Exception
Error contacting local MavensMate server: No JSON object could be decoded
Could not load json response from mavensmate
{'error': 'Request to the local MavensMate server failed. No JSON object could be decoded'}

I don't know if it's useful, the only weird thing I see is that the second route keeps 4 backslashes  instead of 2...

**Comment by joeferraro** [comment]
i think this could have something to do with this issue: https://github.com/joeferraro/MavensMate-SublimeText/issues/682

do you have HTTP_PROXY and HTTPS_PROXY set as environment variable?

**Comment by enriquegq** [comment]
I had them set. I just deleted them and now I'm not able to open the project from MMapp (before I could). And I get this error:
Error initializing project: tunneling socket could not be established, cause=write EPROTO

**Comment by joeferraro** [comment]
hm and you have your proxy configured in mm-app's global settings?

**Comment by enriquegq** [comment]
yes! I had it configured before and I didn't change that. 
(before installing mm-app I had set the environment variables for the Proxy as well as configured on the mm user settings)

**Comment by enriquegq** [comment]
any news about this issue?? It's being very painful not to use the app :(

I still get the same message: "Request to the local MavensMate server failed. No JSON object could be decoded"
And now I found out that I get this error no matter what I do. Even if I click "Open MavensMate UI" or "Open Salesforce org" I get the same.

**Comment by avinashnelluri** [comment]
@enriquegq @joeferraro 

I'm facing exactly the issue. My mavensmate-app is up and running...when I click on refresh from server, this error shows up. I've the proxy settings set up from a long time and until now it was fine. I don't know what happened after installing mavensmate-app. I've updated the proxy settings in mavensmate-app too and created projects usings it.

**Comment by avinashnelluri** [comment]
@enriquegq  @joeferraro  Below you can notice that when I open a project in mavensmate-app and click on open in sublime, still it throws "Could not contact local mavensmate server, please ensure MavensMate-app is installed and running" error.

![error](https://cloud.githubusercontent.com/assets/13437419/10325036/5cd946e2-6c43-11e5-9721-39c6f670eddf.png)

**Comment by enriquegq** [comment]
@avinashnelluri in my case this error doesn't appear and I can easily open the project in sublime.

**Comment by avinashnelluri** [comment]
@enriquegq Even I can open the project directly in sublime, but it throws install mavensmate-app error. So, I opened mavensmate-app. In the menu bar, you can see Open Project option, You will be asked to select the project from drop down (of project folders). After that, click on the menu bar again, this time, you'll see more options. Click on Project and then click on Open in Sublime button. I did this process hoping if I directly open the project from mavensmate-app, I could get rid of that error. But no luck.

**Comment by tjmadsen** [comment]
@enriquegq did you ever figure this out? I'm having this issue now..
