### ISSUE TITLE
MavensMate standalone app feature request - run in background and do not exit on closing the main window

### ISSUE THREAD

**Issue by michalzaganczyk** [joeferraro/MavensMate-Desktop#57]
I think that it would be a great added-value, if this new standalone MM app: 
- could run in the background (minimized to systray) and not close the process when closing the main window
- could be started automatically by SublimeText plugin

**Comment by joeferraro** [comment]
@michalzaganczyk windows i assume?

**Comment by michalzaganczyk** [comment]
Yes, sorry, I didn't mentioned that. It is regarding the Windows 7x64 build, indeed.

**Comment by joeferraro** [comment]
thanks and i agree with this

**Comment by boxfoot** [comment]
+1
