### ISSUE TITLE
Hide Dock Icon - Mac

### ISSUE THREAD

**Issue by P-Krebs** [joeferraro/MavensMate-Desktop#64]
I have a small enhancement. I would be fine with having to keep MavensMate.app open in order to connect to the salesforce server, but I hate having to look at the icon in my dock. I would love it if I had the option to hide the dock icon and just have like a menubar icon or something. Since the app its really just a server with a UI, a menu bar icon would greatly increase how much I enjoy MavensMate.app. I would then be willing to just keep it open always and let it sit in my menu bar instead of having to close and open the app every time I have to work.

**Comment by harshal-gajare** [comment]
+1 . I would like to request this enhancement for the mac too .

**Comment by jacobraccuia** [comment]
+1.  I wish I didn't upgrade because of this.

**Comment by joeferraro** [comment]
@jacobraccuia you're more than welcome to rollback: https://github.com/joeferraro/MavensMate-SublimeText#version-4-no-longer-supported

**Comment by jacobraccuia** [comment]
@joeferraro I know, but you put a lot of time into this and I don't want to be that disrespectful ( although my comment kind of was ).  I appreciate all the work you've done and MM is fantastic as you know :)

**Comment by joeferraro** [comment]
It's no worries, @jacobraccuia. No shame in running v4. It's virtually impossible for me to test every aspect of a major release given the sheer number of variables involved in developing for Salesforce, so the first few weeks can be a little rocky. Thanks for hanging in there :+1:

**Comment by ra-ryan** [comment]
+1. It was a strange transition when upgrading to have to make sure another app was running in order to use Sublime with my SF projects. For now I've worked around this by setting the Mavens app to open at login, but I like to keep my dock lean in terms of the number of apps it shows and I always interact with Mavens through the menu in Sublime so I think the dock icon is not necessary.

**Comment by MrDOS** [comment]
+1. Not sure how easy Electron makes this to do, but it'd be really nice if this were an option.

**Comment by joeferraro** [comment]
fyi: this is one of the top priorities on my side ... but i don't want to release it until it's cross-platform, so not a quick fix

**Comment by P-Krebs** [comment]
I really appreciate that @joeferraro. You probably have better things to work on than fixing my nitpick-y suggestion and I am glad you are taking your time to make it solid. so Thank you!
