### ISSUE TITLE
Cannot start logging

### ISSUE THREAD

**Issue by nwoolls** [joeferraro/MavensMate-Desktop#66]
The menu item ```Debug > Start Logging``` fails for both the Atom and SublimeText plugins, using the latest version of both and the latest MavensMate-app:

```
Could not create Trace Flags: insufficient access rights on cross-reference id: 005B0000001QWtu
{
  "id": "34c10490-6b87-11e5-a0a5-01f7d7d6beb5",
  "complete": true,
  "operation": "start-logging",
  "error": "Could not create Trace Flags: insufficient access rights on cross-reference id: 005B0000001QWtu",
  "stack": "Error: Could not create Trace Flags: insufficient access rights on cross-reference id: 005B0000001QWtu\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/sfdc-client.js:931:20\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/promise/lib/core.js:33:15\n    at flush (/Applications/MavensMate.app/Contents/Resources/app/node_modules/asap/asap.js:27:13)\n    at doNTCallback0 (node.js:416:9)\n    at process._tickCallback (node.js:345:13)",
  "promiseId": "34baea10-6b87-11e5-92a1-ef9623729827"
}
```

**Comment by joeferraro** [comment]
@nwoolls this is a salesforce api error. whose user id is "005B0000001QWtu"?

**Comment by nwoolls** [comment]
There is no user in the DB with that ID.

**Comment by EleazarCrusader** [comment]
I found that I could manually update the User Id in the .debug file located in the root of the project in the config folder under the users node.
````{
    "levels": {
        "Workflow": "INFO",
        "Callout": "INFO",
        "System": "DEBUG",
        "Database": "INFO",
        "ApexCode": "DEBUG",
        "Validation": "INFO",
        "Visualforce": "DEBUG"
    },
    "users": [
        "005j0zzz00BO2yo"
    ],
    "expiration": 480
}
````

**Comment by EleazarCrusader** [comment]
I just found that the MavensMate app has a new area for Debug Logs.  It's in the main drop down in the MavensMate-app.  

The drop down link in the Test tab doesn't seem to work and keeps showing the turn on logging message.

**Comment by omniphx** [comment]
Getting a similar error when trying to call `Debugging > Start logging` from sublime:
```
Operation: Started logging for user ids specified in config/.debug
Timestamp: Wed, 18 Nov 2015 11:33:08
   Result: [ERROR]: Could not create Trace Flags: LogType is required.: LogType
```
My config:
```
{
    "levels": {
        "Workflow": "INFO", 
        "Callout": "INFO", 
        "System": "DEBUG", 
        "Database": "INFO", 
        "ApexCode": "DEBUG", 
        "Validation": "INFO", 
        "Visualforce": "DEBUG"
    }, 
    "users": [
        "005i0000006gLHDAA2"
    ], 
    "expiration": 480
}
```
Windows
MavensMate-app v0.0.10
MavenMate for Sublime Text v7.0.0-beta.1

Looks like I might be missing a key/value from my config file, but tried creating a brand new project and the debug file is the same.

**Comment by omniphx** [comment]
Looks like I'm having the same issue as https://github.com/joeferraro/MavensMate/issues/602

**Comment by zainabShikari** [comment]
i am facing the same issue while executing the start logging command. my config is:


    "users": [
        "00537000000VtMFAA0"
    ],
    "levels": {
        "Workflow": "ERROR",
        "Callout": "ERROR",
        "System": "ERROR",
        "Database": "ERROR",
        "ApexCode": "DEBUG",
        "ApexProfiling": "ERROR",
        "Validation": "ERROR",
        "Visualforce": "ERROR"
    },
    "expiration": 480
}

**Comment by ralphcallaway** [comment]
looks like there are two issues going on here

1) api version issues, with v35 we need to send different data to salesforce, since we weren't you'll get the LogType required error, a patch is in place, but while waiting for it to get released you can switch the api version for mavensmate in the settings to v34 or lower

2) invalid user ids, if the user id isn't valid you'll get the insufficient access right errors. This happens if you put an invalid user in `config/.debug`, or if you've edited your org credentials resulting in a new user id. I've got a patch in place to update the logging user id when your credentials are updated. In the meantime you can just edit `config/.debug` directly to clear out the invalid user id
