### ISSUE TITLE
Tooling API compile fails with managed package dependency 

### ISSUE THREAD

**Issue by TPPickard** [joeferraro/MavensMate-Desktop#72]
I have a batch with a dependency on a managed package which I have defined in my meta.xml. However when I compile with the tooling api I get Package Visibility: Type is not visible but when compiled with the metadata api.

meta.xml

    <apiVersion>33.0</apiVersion>
    <packageVersions>
        <majorNumber>15</majorNumber>
        <minorNumber>15</minorNumber>
        <namespace>echosign_dev1</namespace>
    </packageVersions>
    <status>Active</status>

Tried to search through SFDC's known issues but didn't see anything. Please close if this is on their side. Will attach the log in another post. Its not accepting my attachment right now.

**Comment by TPPickard** [comment]
github is not accepting my txt file copied from the mavesmate log file. Let me know if you want it through another channel.

**Comment by dsharrison** [comment]
This is an issue I have seen with the Tooling API since its release. It does not always happen, but it seems that once it does, it will never go away for that class/page file. The only workaround I have found is to use the metadata api for that project, which is not ideal.

**Comment by TPPickard** [comment]
Weird! I haven't had many classes with managed package dependencies. Thanks!
