### ISSUE TITLE
Switching git branch forces re-entry of credentials on save

### ISSUE THREAD

**Issue by OrnIngvar** [joeferraro/MavensMate-Desktop#78]
I've run into this issue a few times where if I switch a git branch that is connected to a mavensmate project and I try to save a class I am required to re-enter my sfdc credentials even though they have not changed. After I do this I try to save again and I get an invalid cross-reference error. The solution to get past this is to do a clean project and then the save works without issues.

I've made sure that the /config folder is not part of my git branches

OS X El Cap - Mavensmate-app v0.0.10-beta2 - Mavensmate for Sublime v7.0.0-beta.1

p.s. many thanks for a fantastic tool!

**Comment by joeferraro** [comment]
Need a bit more information here. When you switch branches, are you switching orgs?

**Comment by OrnIngvar** [comment]
The org is the same but after switching branches I do run a ant undeploy script which manipulates the org by removing all custom metadata from it and then re deploying everything again. This script does not touch the /config folder so I'm unsure why this happens.

**Comment by OrnIngvar** [comment]
I've started seeing this even when I'm not running the undeploy script. Now I only need to quit sublime and mavensmate app and reopen and when I try to save I'm prompted to re enter my credentials. The only difference is that after entering my credentials now I can save without getting the invalid cross reference id error.

**Comment by milue** [comment]
I ran into a similar issue: 
* switched branches on git (not switching orgs), ran ant script for undeploy & deploy
* trying to save changes in sublime
* received "invalid cross reference id" error

**Comment by e02d96ec16** [comment]
The cross reference id error I encountered appeared when the file on disk was out-of-sync with the one in the org. Was solved with a refresh from server. I don't think it's related to this issue (there's no credentials re-prompting).
