### ISSUE TITLE
Unable to retrieve password from the keychain store

### ISSUE THREAD

**Issue by DarrinDipity** [joeferraro/MavensMate-Desktop#80]
Opened app and created a project.  See the source code from Salesforce on my file system.

Open project folder in Sublime and right click on root folder and select MavensMate > Refresh from server.

The console has the following output:
Operation: Your MavensMate project needs to be upgraded. Opening the upgrade UI.
Timestamp: Thu, 08 Oct 2015 11:21:24
   Result: [OPERATION FAILED]: Unable to retrieve password from the keychain store.

Debug level is SILLY, but I don't see anything relevant to add here.

Running Windows 7 at work (i.e. lots of stuff locked down)

Is there any more info I can pass along?

**Comment by bobbyculbertson** [comment]
I am getting the same error.

Windows 7 machine. 
Upgraded to latest release

Had projects on Mac and on Windows machine.

Have uninstalled on both and reinstalled on Windows only.

Still get same error when trying to save a class

**Comment by cipherstream** [comment]
Same error for me.  I'm on Windows 10 using MavensMate-app v0.0.10.  I only get this when attempting to edit using SublimeText 3, I don't get this issue using Atom.

**Comment by Yorgie** [comment]
Any word on this?  Same error here.  Windows 7, MMv0.0.10, SublimeText 3.
