### ISSUE TITLE
Mavens Mate App appears Blank

### ISSUE THREAD

**Issue by rodriguezartav** [joeferraro/MavensMate-Desktop#81]
Hi - MavensMate upgraded automatically - now the App loads and starts. But screen appears blank.

If I go on the browser and type the url - it works. But it does not work on the app - so I can't do anything. I was using it on production - should not have upgraded on me.

Please help, tried to go back to 4 - but throws errors on some command not found on the list.

Mac osx - Yosemite 

<img width="1015" alt="screen shot 2015-10-08 at 11 44 34 am" src="https://cloud.githubusercontent.com/assets/590173/10374751/0010584a-6db2-11e5-9fe8-88895b4dde6e.png">

**Comment by joeferraro** [comment]
please see instructions for installing v6 (previously 4.0.5): https://github.com/joeferraro/MavensMate-SublimeText#version-6-previously-known-as-v405-stable

**Comment by rodriguezartav** [comment]
Thanks Joe - for all of your great work as well!

Happy to help test as well - I have another computer where I can set it up.

On Thu, Oct 8, 2015 at 12:01 PM, Joe Ferraro <notifications@github.com>
wrote:

> please see instructions for installing v6 (previously 4.0.5):
> https://github.com/joeferraro/MavensMate-SublimeText#version-6-previously-known-as-v405-stable
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joeferraro/MavensMate-app/issues/81#issuecomment-146639104>
> .
>



-- 
Roberto Rodriguez
Programador (Hacker)
Costa Rica
@rodriguezartav
+506 8703 3825

**Comment by joeferraro** [comment]
@rodriguezartav mm-app should certainly not appear blank! if you could set up mm-app on another computer and try to test/debug it, that'd be super helpful. You can toggle the webkit inspector developer tools via the advanced menu.

**Comment by rodriguezartav** [comment]
will do

On Thu, Oct 8, 2015 at 12:20 PM, Joe Ferraro <notifications@github.com>
wrote:

> @rodriguezartav <https://github.com/rodriguezartav> mm-app should
> certainly not appear blank! if you could set up mm-app on another computer
> and try to test/debug it, that'd be super helpful. You can toggle the
> webkit inspector developer tools via the advanced menu.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joeferraro/MavensMate-app/issues/81#issuecomment-146644225>
> .
>



-- 
Roberto Rodriguez
Programador (Hacker)
Costa Rica
@rodriguezartav
+506 8703 3825

**Comment by DarrinDipity** [comment]
On Windows, is this the same problem?  Trying to use the app to open a previously downloaded project.

![image](https://cloud.githubusercontent.com/assets/2822741/10377664/4d0ef9b8-6dca-11e5-8679-d1634058c371.png)

**Comment by joeferraro** [comment]
@DarrinDipity this is typically an issue seen behind firewalls. i don't have a fix at this time.

**Comment by alex-martin-xactium** [comment]
Currently getting this issue again. Can't do anything, including making new projects.
