### ISSUE TITLE
Changing key bindings.

### ISSUE THREAD

**Issue by amorek** [joeferraro/MavensMate-Desktop#88]
Platform: Windows 7 64 bit
MavensMate: v7.0.0-beta1
MavensMate-App:  v0.0.10-beta4
Editor: Sublime Text 3 build 3083

Hello, is there any way to change keys? In version 4/6 Ctrl-Shift-S used to save single file I was working on. Now it saves everything I have opened in tabs, it's kind of annoying as for 99.99% of time I only want to compile file I'm currently working on (for the past few months there might have been 1 or 2 situations where I wanted to save a few files at once).

I'd like to rebind ctrl+shift+s to Compile Active File, is there any way to do that?

Thanks, keep up the good work.

**Comment by joeferraro** [comment]
Hi, can you please update your issue according to the guidelines? thanks! https://github.com/joeferraro/MavensMate-app/blob/master/CONTRIBUTING.md

**Comment by amorek** [comment]
Ok, I hope it's good now.

**Comment by joeferraro** [comment]
HI @amorek, I've never used Ctrl+shift+s to save files, is there any reason ctrl+s does not work for you (this is what I typically use)?

**Comment by amorek** [comment]
I always turn off compile on save option. 
I have a tendency to save files really often, almost after every change, but since salesforce compilation can take from several seconds at best to several minutes in slow environments, I would end up with having several compilations going at the same time which would then result in error.
Prior to MavensMate-app era, I've always developed and saved file locally and then compiled current file with Ctrl+Shift+S when I was ready.
Now I must have only one tab open when I'm developing, because if I had more tabs open, ctrl+shift+s would try to save all of them and I'd eventually end up overwriting other developer's work with my outdated files.

**Comment by joeferraro** [comment]
@amorek ok, thanks for the additional information. This is likely a minor change, let me have a look.

**Comment by deckblad** [comment]
I too was under the impression that ctrl+shit+s would compile only the active tab. You support that in documentation here. http://mavensmate.com/Plugins/Sublime_Text/Shortcuts
What is the proper hotkey supposed to be for saving only the active tab?

**Comment by deckblad** [comment]
Doesn't look like there's any option to compile only the active tab now. Unless compile-on-save is on.

**Comment by amorek** [comment]
For Sublime Text, add this User Key bindings:
{  "keys": ["ctrl+shift+s"], "command": "compile_active_file" }
