### ISSUE TITLE
cant save to salesforce

### ISSUE THREAD

**Issue by textual** [joeferraro/MavensMate-Desktop#95]
looks like its only saving locally, not even trying to send to salesforce. im not sure if this is relevant, but i only have a [name].sublime-project file and the mavensmate app doesnt have the save on compile option. running MavensMate-app v0.0.10 / Sublime 3083 / mac osx 10.10.5. additionally syntax highlighting isnt working either

**Comment by joeferraro** [comment]
what version of the ST plugin are you using?

**Comment by textual** [comment]
im not sure how to answer that question

**Comment by joeferraro** [comment]
Which installation steps did you follow: https://github.com/joeferraro/MavensMate-SublimeText#install

**Comment by textual** [comment]
i had only installed the mavens mate app and sublime, not the sublime mavens mate plugin. i started installing the mavens mate plugin, and now i have syntax highlighting, but my existing projects dont open through the sublime interface.
