### ISSUE TITLE
Unit Tests - run test error 

### ISSUE THREAD

**Issue by francesco-rampoldi** [joeferraro/MavensMate-Desktop#99]
Hi, I updated to version 0.10 and now I get this error when I try to run tests from manensmate app. Invalid URI "/services/data/v34.0/tooling/runTestsAsynchronous"  
![capture](https://cloud.githubusercontent.com/assets/3263930/10698072/6240b92a-79af-11e5-898b-eec2a839df45.PNG)

Is there a workaround to make unit tests run again?

**Comment by EricSSH** [comment]
Any fix for this?

**Comment by gwalliman** [comment]
I just experienced this error; recreated the project and that fixed it. May be worth a try @EricSSH.

**Comment by vassyz** [comment]
I'm experiencing the same issue, but I've just started with MavensMate.
@gwalliman How do you recreate a project?
